### ISSUE TITLE
Gmail 2FA

### ISSUE THREAD

**Issue by Takenfal** [praul/autoreply#10]
What about accessing Gmail accounts protected by 2FA? Is it possible? If not, is there a possible solution for that not including removing the 2FA?
Thanks!

**Comment by praul** [comment]
Have you tried setting up an app-password? https://support.google.com/accounts/answer/185833?hl=en

I haven't tried, but from what I can tell (after reading https://towardsdatascience.com/automate-sending-emails-with-gmail-in-python-449cc0c3c317), with an app password, gmail accepts normal imap / smtp requests.

you would have to use
imap.gmail.com, port 993
and
smtp.gmail.com, port 465
with ssl. 

I don't have time to test it now, but I will report back and update the readme accordingly.
