### ISSUE TITLE
Office 365 - Unable to send responces.

### ISSUE THREAD

**Issue by joshuadenson** [praul/autoreply#9]
Hey, 

I'm working on a problem that this script would work perfectly for but I can't for the life of me get it working with 365.

I've looked though the code and I think it's that STARTTLS isn't being used. 

As a result I get a message that : Trying different subject Wait 10s and retry.

Any input would be appreciated. 

Appreciate the hard work done here

**Comment by praul** [comment]
Hi, thanks for your issue. I'm on vacation but I will implement a better connection handling, once I'm back. You could edit out the try excepts in send_reply, to see actual error messages.

**Comment by praul** [comment]
I can confirm this issue, as for now, I am not able to send mails with starttls. I contacted the author of the mail library autoreply is using for a solution. I will respond back and fix this issue.

**Comment by praul** [comment]
Should be fixed in latest release (1.01)
Please report back if this works for you.

**Comment by joshuadenson** [comment]
Hey,

Thanks so much for this! 

Will do :) Thanks

**Comment by praul** [comment]
@joshuadenson : Did you have a chance to try it out? Is this issue resolved?
